DATA_INFO:
    ANNOTATION_FILE_TRAIN: './data/COCO/COCO_ANNOTATION_TRAIN.txt'
    CACHE_FILE_TRAIN: './data/COCO/COCO_ANNOTATION_TRAIN.cache'
    DATA_ROOT_TRAIN: './data/COCO/train/'
    IMAGE_LIST_TEST: './data/COCO/COCO_VALID_LIST.txt'
    CACHE_FILE_TEST: './data/COCO/COCO_VALID_LIST.cache'
    DATA_ROOT_TEST: './data/COCO/valid/'
    ANNOTATIONS_TEST: './data/COCO/COCO_VALID_2017.json'

RECTANGULAR_INFO:
    RECTANGULAR_TRAINING: 0
    SHAPE_PADDING_TRAIN: 0.0
    RECTANGULAR_TEST: 1
    SHAPE_PADDING_TEST: 0.5

AUGMENT_INFO:
    AUGMENTATION: 1
    MOSAIC_P: 1.0
    MOSAIC_FOUR_P: 0.8
    MIXUP_P: 0.15
    MIXUP_BETA: [32.0, 32.0]
    BORDER_EPS: 0.1
    BORDER_COLOR: [114, 114, 114]
    DEGREE: 0.0
    TRANSLATE: 0.2
    SCALE: 0.9
    SHEAR: 0.0
    PERSPECTIVE: 0.0
    WH_THRESHOLD: 2
    ASPECT_RATIO_THRESHOLD: 20
    AREA_THRESHOLD: 0.1
    AVOID_ZERO_EPS: 0.0000000000000001
    H_GAIN: 0.015
    S_GAIN: 0.7
    V_GAIN: 0.4
    FLIPUD_P: 0.0
    FLIPLR_P: 0.5

ANCHORS: [[12, 16, 19, 36, 40, 28], [36, 75, 76, 55, 72, 146], [142, 110, 192, 243, 459, 401]]
NUM_CLASSES: 80
STRIDE: [8, 16, 32]
NORMINAL_BATCH_SIZE: 64

LOSS_INFO:
    CLASS_POSITIVE_WEIGHT: 1.0
    OBJECT_POSITIVE_WEIGHT: 1.0
    GRID_BIAS: 0.5
    ANCHOR_T: 4.0
    AVOID_ZERO_EPS: 0.00000001
    PAIRWISE_IOU_K: 10
    COST_PAIRWISE_IOU_LOSS_WEIGHT: 3.0
    IOU_LOSS_TYPE: 'CIOU'
    IOU_LOSS_RATIO: 1.0
    LOSS_BALANCE: [4.0, 1.0, 0.4]
    BOX_GAIN: 0.05
    CLASS_GAIN: 0.3
    OBJECT_GAIN: 0.7

TRAINING_INFO:
    WEIGHT_DECAY: 0.0005
    LR_INIT: 0.01
    MOMENTUM: 0.937
    LR_F: 0.1
    WARMUP_EPOCHS: 3
    WARMUP_BIAS_LR: 0.1
    WARMUP_MOMENTUM: 0.8

EMA_INFO:
    UPDATES: 0
    DECAY: 0.9999
    TAU: 2000

NMS_INFO:
    CONFIDENCE_THRESHOLD: 0.001
    IOU_THRESHOLD: 0.65
    CLASS_OFFSET: 4096
    MAX_DETECTION: 300
    MAX_BOX: 30000

